### ISSUE TITLE
test failure (StackOverflowError) with latest ScalaCheck 

### ISSUE THREAD

**Issue by SethTisue** [circe/circe#1084]
in the Scala community build, after recent commits to https://github.com/scalacheck/scalacheck's master branch I started seeing:

```
[circe] [info] JsonCodecMacrosSuite:
[circe] [info] io.circe.generic.JsonCodecMacrosSuite *** ABORTED ***
[circe] [info]   java.lang.StackOverflowError:
[circe] [info]   at io.circe.generic.jsoncodecmacrossuiteaux.SelfRecursiveWithOption$.atDepth(JsonCodecMacrosSuite.scala:145)
[circe] [info]   at io.circe.generic.jsoncodecmacrossuiteaux.SelfRecursiveWithOption$.$anonfun$arbitrarySelfRecursiveWithOption$1(JsonCodecMacrosSuite.scala:154)
[circe] [info]   at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary$lzycompute(Arbitrary.scala:75)
[circe] [info]   at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary(Arbitrary.scala:75)
[circe] [info]   at org.scalacheck.ArbitraryLowPriority.$anonfun$arbOption$1(Arbitrary.scala:339)
[circe] [info]   at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary$lzycompute(Arbitrary.scala:75)
[circe] [info]   at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary(Arbitrary.scala:75)
[circe] [info]   at org.scalacheck.ArbitraryLowPriority.arbitrary(Arbitrary.scala:79)
[circe] [info]   at org.scalacheck.ArbitraryLowPriority.arbitrary$(Arbitrary.scala:79)
[circe] [info]   at org.scalacheck.Arbitrary$.arbitrary(Arbitrary.scala:62)
[circe] [info]   ...
[circe] [info] SemiautoDerivedSuite:
[circe] [info] io.circe.generic.JsonCodecMacrosSuite *** ABORTED ***
[circe] [info]   java.lang.StackOverflowError:
[circe] [info]   at io.circe.generic.jsoncodecmacrossuiteaux.SelfRecursiveWithOption$.atDepth(JsonCodecMacrosSuite.scala:145)
[circe] [info]   at io.circe.generic.jsoncodecmacrossuiteaux.SelfRecursiveWithOption$.$anonfun$arbitrarySelfRecursiveWithOption$1(JsonCodecMacrosSuite.scala:154)
[circe] [info]   at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary$lzycompute(Arbitrary.scala:75)
[circe] [info]   at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary(Arbitrary.scala:75)
[circe] [info]   at org.scalacheck.ArbitraryLowPriority.$anonfun$arbOption$1(Arbitrary.scala:339)
[circe] [info]   at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary$lzycompute(Arbitrary.scala:75)
[circe] [info]   at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary(Arbitrary.scala:75)
[circe] [info]   at org.scalacheck.ArbitraryLowPriority.arbitrary(Arbitrary.scala:79)
[circe] [info]   at org.scalacheck.ArbitraryLowPriority.arbitrary$(Arbitrary.scala:79)
[circe] [info]   at org.scalacheck.Arbitrary$.arbitrary(Arbitrary.scala:62)
[circe] [info]   ...
[circe] [info] io.circe.generic.SemiautoDerivedSuite *** ABORTED ***
[circe] [info]   java.lang.StackOverflowError:
[circe] [info]   at org.scalacheck.ArbitraryLowPriority.arbOption(Arbitrary.scala:339)
[circe] [info]   at org.scalacheck.ArbitraryLowPriority.arbOption$(Arbitrary.scala:338)
[circe] [info]   at org.scalacheck.Arbitrary$.arbOption(Arbitrary.scala:62)
[circe] [info]   at io.circe.generic.SemiautoDerivedSuite$RecursiveWithOptionExample$.atDepth(SemiautoDerivedSuite.scala:64)
[circe] [info]   at io.circe.generic.SemiautoDerivedSuite$RecursiveWithOptionExample$.$anonfun$arbitraryRecursiveWithOptionExample$1(SemiautoDerivedSuite.scala:71)
[circe] [info]   at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary$lzycompute(Arbitrary.scala:75)
[circe] [info]   at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary(Arbitrary.scala:75)
[circe] [info]   at org.scalacheck.ArbitraryLowPriority.$anonfun$arbOption$1(Arbitrary.scala:339)
[circe] [info]   at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary$lzycompute(Arbitrary.scala:75)
[circe] [info]   at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary(Arbitrary.scala:75)
[circe] [info]   ...
```

at e.g. https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4199/consoleFull

this is the kind of thing where I feel I should report it _somewhere_, but I don't know where. is it a regression in ScalaCheck? or is the actual bug here in this repo?

there is no ScalaCheck release that includes these changes, but I expect the problem would be reproducible by `publishLocal`ing one and then using it here

**Comment by SethTisue** [comment]
I dealt with in the community build by freezing our config at an older commit: https://github.com/scala/community-builds/pull/870

**Comment by travisbrown** [comment]
I respect the community build mission, I guess, but I don't really want to be on the hook for compatibility with arbitrary changes in ScalaCheck master, especially since circe is still on the ancient 1.13.5 thanks to cats-testing and ScalaTest.

**Comment by SethTisue** [comment]
yes, that makes sense.

I'm fine with sticking with the frozen ScalaCheck, we have many frozen projects for various reasons, it's normal.
