### ISSUE TITLE
JSON malformed message body

### ISSUE THREAD

**Issue by tampler** [circe/circe#1146]
Hello I'm getting an error parsing JSON in a test, which uses ZIO and http4s projects. I get the error below for both Circe 0.11.1 and 0.12.0-M2. Here's my code:
```scala
    it("should parse json") {
      
    val body = json"""
      {
        "id"        : 33        ,
        "url"       :"/testUrl" ,
        "title"     :"One"      ,
        "completed" : false     ,
        "order"     : "None"
      }"""

    val req = request[TodoTask](Method.POST, "/").withEntity(body)
```
For which I get the following err:
```bash
Fiber failed.
A checked error was not handled.
org.http4s.MalformedMessageBodyFailure: Malformed message body: Invalid JSON
        at org.http4s.circe.CirceInstances$.$anonfun$defaultCirceParseError$1(CirceInstances.scala:179)
        at cats.syntax.EitherOps$.leftMap$extension(either.scala:144)
        at org.http4s.circe.CirceInstances.$anonfun$jsonDecoderByteBufferImpl$1(CirceInstances.scala:37)
        at scala.util.Either.flatMap(Either.scala:341)
        at cats.data.EitherT.$anonfun$subflatMap$1(EitherT.scala:109)
```

I opened an issue in the http4s project as well. Any clues ?

**Comment by plokhotnyuk** [comment]
@tampler Just for debugging purpose you can use [jsoniter-scala](https://github.com/plokhotnyuk/jsoniter-scala) :) 

It reports errors clearly with a position and a dump of the buffer part where they occurs, like here:

```
expected '{', offset: 0x00000000, buf:
+----------+-------------------------------------------------+------------------+
|          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f | 0123456789abcdef |
+----------+-------------------------------------------------+------------------+
| 00000000 | 48 54 54 50 2f 31 2e 30 20 32 30 30 20 4f 4b 0a | HTTP/1.0 200 OK. |
| 00000010 | 43 6f 6e 74 65 6e 74 2d 54 79 70 65 3a 20 61 70 | Content-Type: ap |
| 00000020 | 70 6c 69 63 61 74 69 6f 6e 2f 6a 73 6f 6e 0a 43 | plication/json.C |
+----------+-------------------------------------------------+------------------+
```
```
expected '"', offset: 0x0000003e, buf:
+----------+-------------------------------------------------+------------------+
|          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f | 0123456789abcdef |
+----------+-------------------------------------------------+------------------+
| 00000010 | 32 37 36 38 2c 22 69 22 3a 2d 32 31 34 37 34 38 | 2768,"i":-214748 |
| 00000020 | 33 36 34 38 2c 22 6c 22 3a 2d 39 32 32 33 33 37 | 3648,"l":-922337 |
| 00000030 | 32 30 33 36 38 35 34 37 37 35 38 30 38 2c 27 62 | 2036854775808,'b |
| 00000040 | 6c 27 3a 74 72 75 65 2c 22 63 68 22 3a 22 56 22 | l':true,"ch":"V" |
| 00000050 | 2c 22 64 62 6c 22 3a 2d 31 32 33 34 35 36 37 38 | ,"dbl":-12345678 |
+----------+-------------------------------------------------+------------------+
```

**Comment by travisbrown** [comment]
I don't think the issue here is really circe-specific at all, or only in a round-about way. At a glance it looks like you're trying to post a JSON object with an `"order": "None"` field to be decoded as a case class with an `order: Option[Int]` member. This will fail during decoding, since there's no mapping between strings and `Option` values: instead a JSON `null` (or a missing field) gets decoded to a Scala `None`, and a present value gets decoded to `Some`.

You can see this by minimizing the issue:

```scala
import io.circe.generic.auto._, io.circe.literal._

val body = json"""
      {
        "id"        : 33        ,
        "url"       :"/testUrl" ,
        "title"     :"One"      ,
        "completed" : false     ,
        "order"     : "None"
      }"""

final case class TodoItemPostForm(
  title: String,
  order: Option[Int] = None
)

body.as[TodoItemPostForm]
```
…which will give you an `DecodingFailure(Int, List(DownField(order)))` indicating that the problem is that the `order` field.

The actual error is getting buried somewhere in your test code, which has several layers of abstraction that I can't wade through at the moment, but if you look at the actual http4s response value from that POST request I bet there's something at least a little more useful there.
