### ISSUE TITLE
Investigate flaky JavaTimeCodecSuite test

### ISSUE THREAD

**Issue by travisbrown** [circe/circe#1635]
From [this build](https://github.com/circe/circe/pull/1634/checks?check_run_id=1654132929):

```
io.circe.JavaTimeCodecSuite:
  + Codec[Instant]: codec.consistency with accumulating 0.028s
  + Codec[Instant]: codec.decoder serializability 0.006s
  + Codec[Instant]: codec.encoder serializability 0.001s
  + Codec[Instant]: codec.roundTrip 0.013s
  + Codec[LocalDateTime]: codec.consistency with accumulating 0.027s
  + Codec[LocalDateTime]: codec.decoder serializability 0.001s
  + Codec[LocalDateTime]: codec.encoder serializability 0.001s
  + Codec[LocalDateTime]: codec.roundTrip 0.012s
  + Codec[ZonedDateTime]: codec.consistency with accumulating 0.014s
  + Codec[ZonedDateTime]: codec.decoder serializability 0.001s
  + Codec[ZonedDateTime]: codec.encoder serializability 0.001s
failing seed for codec.roundTrip is S4XXC9Cf0UdHTtBK_lJtDeb5SOqZuEBwlUtsXQ2yljB=
==> X io.circe.JavaTimeCodecSuite.Codec[ZonedDateTime]: codec.roundTrip  0.056s munit.FailException: /home/runner/work/circe/circe/modules/tests/shared/src/test/scala/io/circe/JavaTimeCodecSuite.scala:117
116:  checkAll("Codec[LocalDateTime]", CodecTests[LocalDateTime].codec)
117:  checkAll("Codec[ZonedDateTime]", CodecTests[ZonedDateTime].codec)
118:  checkAll("Codec[OffsetDateTime]", CodecTests[OffsetDateTime].codec)

Failing seed: T8DQ5nIKa8aC5z5IgJgMQMWZ-8ijkUNRAXQw-6JRmzH=
You can reproduce this failure by adding the following override to your suite:

  override val scalaCheckInitialSeed = "T8DQ5nIKa8aC5z5IgJgMQMWZ-8ijkUNRAXQw-6JRmzH="

Falsified after 90 passed tests.
> Labels of failing property: 
Expected: Right(2827-11-07T01:50:49-07:00[Canada/Mountain])
Received: Right(2827-11-07T01:50:49-06:00[Canada/Mountain])
> ARG_0: 2827-11-07T01:50:49-07:00[Canada/Mountain]
    at munit.Assertions.fail(Assertions.scala:261)
    at munit.Assertions.fail$(Assertions.scala:255)
    at munit.FunSuite.fail(FunSuite.scala:11)
    at munit.ScalaCheckSuite.$anonfun$propToTry$4(ScalaCheckSuite.scala:104)
    at scala.util.Try$.apply(Try.scala:210)
    at munit.ScalaCheckSuite.propToTry(ScalaCheckSuite.scala:104)
    at munit.ScalaCheckSuite.$anonfun$scalaCheckPropTransform$3(ScalaCheckSuite.scala:46)
    at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:439)
    at munit.Suite$$anon$1.execute(Suite.scala:26)
    at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:393)
    at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:302)
    at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallbacks(Promise.scala:276)
    at scala.concurrent.impl.Promise$DefaultPromise.transform(Promise.scala:128)
    at munit.internal.FutureCompat$ExtensionFuture.transformCompat(FutureCompat.scala:16)
    at munit.ScalaCheckSuite.$anonfun$scalaCheckPropTransform$2(ScalaCheckSuite.scala:48)
    at munit.GenericTest.$anonfun$withBodyMap$1(GenericTest.scala:33)
    at munit.MUnitRunner.$anonfun$runTestBody$1(MUnitRunner.scala:296)
```

**Comment by rodant** [comment]
Hi, I'm unsure if it relates to this, but I came across a similar issue. In my case, a milliseconds counter in the ISO string isn't processed correctly. See this test showing the error:

```
import org.scalatest.funspec.AnyFunSpec
import io.circe.parser.parse
import io.circe.syntax._
import io.circe.generic.auto._
import org.scalatest.EitherValues

import java.time.ZonedDateTime

class JavaTimeCodecTest extends AnyFunSpec with EitherValues {
  case class TestEntity(id: String, time1: ZonedDateTime, time2: ZonedDateTime)

  it("generate the same json") {
    val okDateTime    = "2018-09-02T16:36:28.261+02:00"
    val buggyDateTime = "2018-09-02T16:36:28.260+02:00"
    val jsonStr =
      s"""
         |{
         | "id": "1",
         | "time1": "$okDateTime",
         | "time2": "$buggyDateTime"
         |}
         |""".stripMargin

    val time1  = ZonedDateTime.parse(okDateTime)
    val time2  = ZonedDateTime.parse(buggyDateTime)
    val entity = TestEntity("1", time1, time2)

    assertResult(parse(jsonStr).value) {
      entity.asJson
    }
  }
}

```

**Comment by longliveenduro** [comment]
@rodant I did let your test run. The times created by circe are correct, they are just formatted differently (trailing zeros in nanos (correction: millis, see below) are omitted by circes json renderer):

```
Expected {
  "id" : "1",
  "time1" : "2018-09-02T16:36:28.261+02:00",
  "time2" : "2018-09-02T16:36:28.260+02:00"
}, but got {
  "id" : "1",
  "time1" : "2018-09-02T16:36:28.261+02:00",
  "time2" : "2018-09-02T16:36:28.26+02:00"
}
```

**Comment by rodant** [comment]
Hi Chris @longliveenduro, for my understanding the digits after the dot are the milliseconds and it is not the same 260 millis and 26 millis.

**Comment by longliveenduro** [comment]
Hi Antonion @rodant.

Oh sorry, you are right. I mixed up nanos with millis.
 Please replace "nanos" in my comment above with millis.

But this leads just to the same outcome.

Consider (and try out) this Scala 3 Worksheet:

```
import java.time.OffsetDateTime

val time1 = OffsetDateTime.parse("2018-09-02T16:36:28.260+02:00")
val time2 = OffsetDateTime.parse("2018-09-02T16:36:28.26+02:00")
val time3 = OffsetDateTime.parse("2018-09-02T16:36:28.2600+02:00")


println(time1 == time2)
println(time1 == time3)
```

The output is:
```
val time1: java.time.OffsetDateTime = 2018-09-02T16:36:28.260+02:00
val time2: java.time.OffsetDateTime = 2018-09-02T16:36:28.260+02:00
val time3: java.time.OffsetDateTime = 2018-09-02T16:36:28.260+02:00

true
true
```
The trap here is, that after the dot we enter fractional decimal digits, and there 0.260 millis are the same as 0.26 millis and 0.2600 millis, as you can see above.

**Comment by rodant** [comment]
Ah, thanks for this peace of code. Without it I wouldn't believe it. I thought the three digits after the dot are the number of milliseconds, but as you found out, it is the fractional of a second: 0.260 seconds = 0.26 seconds and are 260 milliseconds.

Nevertheless the handling is different with joda-time, we didn't have the issue there.

Then we can close this issue and we lern something new :-)
