### ISSUE TITLE
Decoding fields with common prefix and dash does not work

### ISSUE THREAD

**Issue by vbmacher** [circe/circe#1774]
Hello,
I've run into peculiar issue. Imagine the following code:

```scala
package com.github.mypackage

case class A(text: String)
case class B(`a-ha`: String, a: A)


import io.circe.parser._
import io.circe.generic.auto._

val msg =
  """
     { "a-ha": "foo", "a": {"text": "foofoo" } }
  """
println(decode[B](msg))
```

When running this, I got the following exception (the code was run in scala-test so line numbers don't fit):

```
class java.lang.String cannot be cast to class com.github.mypackage.A (java.lang.String is in module java.base of loader 'bootstrap'; com.github.mypackage.A is in unnamed module of loader 'app')
java.lang.ClassCastException: class java.lang.String cannot be cast to class com.github.mypackage.A (java.lang.String is in module java.base of loader 'bootstrap'; com.github.mypackage.A is in unnamed module of loader 'app')
	at com.github.mypackage.B.<init>(ParsingSpec.scala:11)
	at com.github.mypackage.ParsingSpec$anon$importedDecoder$macro$15$1$anon$macro$7$1.from(ParsingSpec.scala:25)
	at com.github.mypackage.ParsingSpec$anon$importedDecoder$macro$15$1$anon$macro$7$1.from(ParsingSpec.scala:25)
	at shapeless.LabelledGeneric$$anon$1.from(generic.scala:229)
	at shapeless.LabelledGeneric$$anon$1.from(generic.scala:226)
	at io.circe.generic.decoding.DerivedDecoder$$anon$1.apply(DerivedDecoder.scala:15)
	at io.circe.Decoder.decodeJson(Decoder.scala:86)
	at io.circe.Decoder.decodeJson$(Decoder.scala:86)
	at io.circe.generic.decoding.DerivedDecoder.decodeJson(DerivedDecoder.scala:6)
	at io.circe.Parser.finishDecode(Parser.scala:13)
	at io.circe.Parser.finishDecode$(Parser.scala:9)
	at io.circe.parser.package$.finishDecode(package.scala:5)
	at io.circe.Parser.decode(Parser.scala:29)
	at io.circe.Parser.decode$(Parser.scala:28)
	at io.circe.parser.package$.decode(package.scala:5)
...
```

The problem is when there are fields with common prefix and the suffix of the longer one starts with dash. This means, for example, that if we had these case classes:

```scala
case class A(text: String)
case class B(`aha`: String, a: A)
``` 

(note field `aha` without dash) - then decoding works as expected.

**Comment by vbmacher** [comment]
Also, plain `case class B(`a-ha`: String)` works well

**Comment by travisbrown** [comment]
@vbmacher What versions (Scala, Circe, Shapeless) are you using? This looks similar to #665, which is due to a bug in the compiler that should be fixed in the latest 2.13 (I have no idea whether the fix has been or will be backported for 2.12).

**Comment by vbmacher** [comment]
Oh I see. It could be it... I use:
- Scala 2.12.12
- circe 0.13.0
- shapeless the one embedded in circe: 2.3.4

I will try it with Scala 2.13 and let you know.

**Comment by travisbrown** [comment]
I just checked a REPL and I can reproduce it with 2.12.13 but not 2.12.14, so you might just try updating to that.

**Comment by vbmacher** [comment]
Cool! That would save me lot of time. Thanks a lot!

**Comment by vbmacher** [comment]
It works, thanks again. I suggest to close the ticket now..

**Comment by travisbrown** [comment]
Sure! Thanks for reminding me of this ridiculous bug. :)
