### ISSUE TITLE
`StackOverflowError` if local class since 0.14.7 with Scala 3

### ISSUE THREAD

**Issue by xuwei-k** [circe/circe#2263]
build.sbt

```scala
libraryDependencies += "io.circe" %% "circe-generic" % "0.14.7"

scalaVersion := "3.3.3"

run / fork := true
```

Main.scala

```scala
package example

import io.circe.Decoder
import io.circe.Json
import io.circe.generic.semiauto._
import io.circe.syntax._

object Main {
  def main(args: Array[String]): Unit = {
    case class A(x: Int)
    object A {
      implicit val decoder: Decoder[A] = deriveDecoder[A]
    }

    println(Json.obj("x" -> Json.fromInt(3)).as[A])
  }
}
```

`sbt run` result

```
[info] running (fork) example.Main 
[error] Exception in thread "main" java.lang.StackOverflowError
[error] 	at example.Main$.example$Main$$$_$A$2(Main.scala:11)
[error] 	at example.Main$A$3$.<init>(Main.scala:12)
[error] 	at example.Main$.A$lzyINIT1$1(Main.scala:11)
[error] 	at example.Main$.example$Main$$$_$A$2(Main.scala:11)
[error] 	at example.Main$A$3$.<init>(Main.scala:12)
[error] 	at example.Main$.A$lzyINIT1$1(Main.scala:11)
[error] 	at example.Main$.example$Main$$$_$A$2(Main.scala:11)
[error] 	at example.Main$A$3$.<init>(Main.scala:12)
[error] 	at example.Main$.A$lzyINIT1$1(Main.scala:11)
[error] 	at example.Main$.example$Main$$$_$A$2(Main.scala:11)
[error] 	at example.Main$A$3$.<init>(Main.scala:12)
[error] 	at example.Main$.A$lzyINIT1$1(Main.scala:11)
[error] 	at example.Main$.example$Main$$$_$A$2(Main.scala:11)
[error] 	at example.Main$A$3$.<init>(Main.scala:12)
[error] 	at example.Main$.A$lzyINIT1$1(Main.scala:11)
[error] 	at example.Main$.example$Main$$$_$A$2(Main.scala:11)
```

**Comment by mrdziuban** [comment]
I'm looking into this and why 0.14.6 didn't have the problem. It doesn't seem to be specific to circe though, summoning a `Mirror` for a local class causes the same error

```scala
package example

import scala.deriving.Mirror

object Main {
  def main(args: Array[String]): Unit = {
    case class A(x: Int)
    object A {
      val mirror = summon[Mirror.ProductOf[A]]
    }

    println(A.mirror)
  }
}
```

yields

```
[info] running example.Main
Exception in thread "sbt-bg-threads-15" java.lang.StackOverflowError
	at example.Main$.example$Main$$$_$A$2(Main.scala:8)
	at example.Main$A$3$.<init>(Main.scala:9)
	at example.Main$.A$lzyINIT1$1(Main.scala:8)
	at example.Main$.example$Main$$$_$A$2(Main.scala:8)
	at example.Main$A$3$.<init>(Main.scala:9)
	at example.Main$.A$lzyINIT1$1(Main.scala:8)
	at example.Main$.example$Main$$$_$A$2(Main.scala:8)
	at example.Main$A$3$.<init>(Main.scala:9)
	at example.Main$.A$lzyINIT1$1(Main.scala:8)
	at example.Main$.example$Main$$$_$A$2(Main.scala:8)
	at example.Main$A$3$.<init>(Main.scala:9)
	at example.Main$.A$lzyINIT1$1(Main.scala:8)
```

**Comment by mrdziuban** [comment]
Opened https://github.com/scala/scala3/issues/20416
