### ISSUE TITLE
Trouble when decode json with circe 0.6.1 on android

### ISSUE THREAD

**Issue by alainmarcel26** [circe/circe#518]
Hi
I'm working with circe 0.6.1 and scala 2.11.
On platform other than android, it is ok.
On android (marshmallow), encoding is ok but decoding works only in debug mode, if I put a breakpoint on line containing decode method.
I use Android Studio. I do not use Proguard.
Find bellow code with description of error, and traceback.
If you have any idea about issue, I can test any new code on my platform.
Very thanks for any help.
Alain.

Scala code
=========
    case class Person(name: String, town: String)

    def testCirce() {
        // The encode works every time.
        {
            import io.circe.generic.auto._
            import io.circe.syntax._

            val obj = Person("Bill", "Paris")
            val s = obj.asJson.noSpaces
            assert(s == """{"name":"Bill","town":"Paris"}""")
        }

        // The decode works only if I put a breakpoint on line containing decode method
        // and I go to the next line in one step (click on Resume button also generate error).
        // Notes
        //        - If I uncomment implicit decoder, then behavior is identical.
        //        - If I remove property town from Person then decode works every time.
        {
            import io.circe.Decoder
            import io.circe.parser.decode
            import io.circe.generic.auto._

            //implicit val personDecoder: Decoder[Person] = {
            //    Decoder.forProduct2("name", "town")(Person.apply)
            //}

            val s = """ { "name": "Bill", "town": "Paris" }"""
            val either = decode[Person](s)
            val obj = either.right.get

            assert(obj == Person("Bill", "Paris"))
        }
    }

Traceback
========
D/AndroidRuntime: Shutting down VM
                  --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: ..., PID: 4273
                  java.lang.RuntimeException: Unable to create App: java.lang.ClassCastException: java.lang.Double cannot be cast to shapeless.HList
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4560)
                      at android.app.ActivityThread.access$1500(ActivityThread.java:151)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5258)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                   Caused by: java.lang.ClassCastException: java.lang.Double cannot be cast to shapeless.HList
                      at io.circe.generic.decoding.ReprDecoder$$anonfun$consResults$1.apply(ReprDecoder.scala:26)
                      at scala.Function2$class.apply$mcVDD$sp(Function2.scala:33)
                      at scala.runtime.AbstractFunction2.apply$mcVDD$sp(AbstractFunction2.scala:12)
                      at cats.Apply$$anonfun$map2$1.apply(Apply.scala:34)
                      at cats.Apply$$anonfun$map2$1.apply(Apply.scala:34)
                      at scala.util.Either$RightProjection.map(Either.scala:535)
                      at cats.instances.EitherInstances$$anon$1.map(either.scala:46)
                      at cats.instances.EitherInstances$$anon$1.map(either.scala:32)
                      at cats.Apply$class.map2(Apply.scala:34)
                      at cats.instances.EitherInstances$$anon$1.map2(either.scala:32)
                      at io.circe.generic.decoding.ReprDecoder$.consResults(ReprDecoder.scala:26)
                      at App$anon$exportDecoder$macro$23$1$$anon$3.apply(App.scala:160)
                      at io.circe.generic.decoding.DerivedDecoder$$anon$1.apply(DerivedDecoder.scala:13)
                      at io.circe.Decoder$class.decodeJson(Decoder.scala:42)
                      at io.circe.generic.decoding.DerivedDecoder.decodeJson(DerivedDecoder.scala:6)
                      at io.circe.Parser$class.decode(Parser.scala:10)
                      at io.circe.parser.package$.decode(package.scala:5)
                      at App.testCirce(App.scala:160)
                      at App.onCreate(App.scala:79)
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4557)
                      at android.app.ActivityThread.access$1500(ActivityThread.java:151)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5258)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
I/art: Thread[5,tid=4281,WaitingInMainSignalCatcherLoop,Thread*=0xf8cda7a0,peer=0x32c030a0,"Signal Catcher"]: reacting to signal 3

**Comment by travisbrown** [comment]
I'm happy to revisit this with a more complete reproducible example.
