### ISSUE TITLE
Problem: Passing `null` to `Encoder#encodeObject`'s Input Case Class Throws

### ISSUE THREAD

**Issue by kevinmeredith** [circe/circe#538]
Using:

```
$cat build.sbt 
scalaVersion := "2.12.1"

val circeVersion = "0.6.1"

libraryDependencies ++= Seq(
  "io.circe" %% "circe-core",
  "io.circe" %% "circe-generic",
  "io.circe" %% "circe-parser"
).map(_ % circeVersion)
```

I observed the following `MatchError` when passing a `null` to `Encoder#encodeObject`:

```
$sbt console

// ...

scala> :paste
// Entering paste mode (ctrl-D to finish)

import io.circe._, io.circe.generic.semiauto._

case class X(a: Int)
case class Y(x: X)

implicit val xEncoder = deriveEncoder[X]

deriveEncoder[Y].encodeObject(Y(null))

// Exiting paste mode, now interpreting.

scala.MatchError: null
  at anon$lazy$macro$36$1$anon$macro$32$1.to(<pastie>:16)
  at anon$lazy$macro$36$1$anon$macro$32$1.to(<pastie>:16)
  at shapeless.LabelledGeneric$$anon$1.to(generic.scala:228)
  at shapeless.LabelledGeneric$$anon$1.to(generic.scala:226)
  at io.circe.generic.encoding.DerivedObjectEncoder$$anon$1.encodeObject(DerivedObjectEncoder.scala:13)
  at io.circe.ObjectEncoder.apply(ObjectEncoder.scala:12)
  at io.circe.ObjectEncoder.apply$(ObjectEncoder.scala:12)
  at io.circe.generic.encoding.DerivedObjectEncoder.apply(DerivedObjectEncoder.scala:6)
  at anon$lazy$macro$46$1$$anon$2.encodeObject(<pastie>:20)
  at anon$lazy$macro$46$1$$anon$2.encodeObject(<pastie>:20)
  at io.circe.generic.encoding.DerivedObjectEncoder$$anon$1.encodeObject(DerivedObjectEncoder.scala:13)
  ... 45 elided
```

I'm not sure if this behavior is standard or documented, however I recently encountered it when playing with this library.

Perhaps `null` is a more appropriate JSON value?

**Comment by travisbrown** [comment]
This is the intended behavior for all methods in circe (and matches most standard library methods, etc.). Checking for null everywhere would be noisy and wouldn't encourage good practice, so it's assumed that the user is responsible for not passing it, and if they do the behavior is undefined (but will usually either be this match error or an NPE).
