### ISSUE TITLE
Exceptions when parsing invalid BiggerDecimal

### ISSUE THREAD

**Issue by SamSchlegel** [circe/circe#600]
```scala
scala> import io.circe.numbers.BiggerDecimal
import io.circe.numbers.BiggerDecimal

scala> BiggerDecimal.parseBiggerDecimal("123.")
java.lang.NumberFormatException: For input string: "123."
  at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
  at java.lang.Integer.parseInt(Integer.java:580)
  at java.math.BigInteger.<init>(BigInteger.java:461)
  at java.math.BigInteger.<init>(BigInteger.java:597)
  at io.circe.numbers.BiggerDecimal$.parseBiggerDecimalUnsafe(BiggerDecimal.scala:345)
  at io.circe.numbers.BiggerDecimal$.parseBiggerDecimal(BiggerDecimal.scala:230)
  ... 42 elided

scala> BiggerDecimal.parseBiggerDecimal("123e")
java.lang.NumberFormatException: For input string: "123e"
  at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
  at java.lang.Integer.parseInt(Integer.java:580)
  at java.math.BigInteger.<init>(BigInteger.java:461)
  at java.math.BigInteger.<init>(BigInteger.java:597)
  at io.circe.numbers.BiggerDecimal$.parseBiggerDecimalUnsafe(BiggerDecimal.scala:345)
  at io.circe.numbers.BiggerDecimal$.parseBiggerDecimal(BiggerDecimal.scala:230)
  ... 42 elided

scala> BiggerDecimal.parseBiggerDecimal("123e-")
java.lang.NumberFormatException: Zero length BigInteger
  at java.math.BigInteger.<init>(BigInteger.java:430)
  at java.math.BigInteger.<init>(BigInteger.java:597)
  at io.circe.numbers.BiggerDecimal$.parseBiggerDecimalUnsafe(BiggerDecimal.scala:352)
  at io.circe.numbers.BiggerDecimal$.parseBiggerDecimal(BiggerDecimal.scala:230)
  ... 42 elided

```
Noticed this when trying to decode `"123."` into a `Long`, which in my case was invalid user input. Should either instead return `DecodingFailure`, or in the case of the first strip the `.` before parsing, but I'm learning towards the former.

This could be fixed by treating all `AFTER_*`as failure states. Can test this and put up a PR tomorrow

**Comment by travisbrown** [comment]
Eek, yeah, this is really bad. The correct behavior should be for `parseBiggerDecimal` to return `None` and the unsafe version to return `null`.

Fortunately this doesn't affect the handling of JSON numbers, where the parser will catch the error, but it does affect the case where users try to decode JSON strings as numeric types, which is much less used. Still, we should get this backported to an 0.7.1 release as soon as possible.

**Comment by travisbrown** [comment]
@SamSchlegel Do you think you'll have time to put together a fix? I'm also happy to take care of it today.

**Comment by SamSchlegel** [comment]
Yep, working on it right now.
