### ISSUE TITLE
Circe 0.9.0-M2, functor Invariant not found

### ISSUE THREAD

**Issue by MeerKatDev** [circe/circe#780]
Hello,
just upgraded to this new version (0.9.0-M2), and I get this error upon testing the code here:
     https://stackoverflow.com/a/46256219/1096030
```

  at org.packag3.controllers.Utils.$anonfun$camelizeJsonKeys$7(Utils.scala:53)
[info]   at io.circe.Json.arrayOrObject(Json.scala:55)
[info]   at org.packag3.controllers.Utils.transformKeys$1(Utils.scala:53)
[info]   at org.packag3.controllers.Utils.camelizeJsonKeys(Utils.scala:57)
[info]   at org.packag3.controllers.Utils.camelizeJsonKeys$(Utils.scala:40)
[info]   at org.packag3.controllers.BaseController.camelizeJsonKeys(BaseController.scala:15)
[info]   at org.packag3.controllers.BaseController.$anonfun$insert$3(BaseController.scala:68)
[info]   at scala.util.Try$.apply(Try.scala:209)
[info]   at org.packag3.controllers.BaseController.$anonfun$insert$2(BaseController.scala:68)
[info]   ...
[info]   Cause: java.lang.ClassNotFoundException: cats.functor.Invariant
[info]   at java.net.URLClassLoader.findClass(Unknown Source)
[info]   at java.lang.ClassLoader.loadClass(Unknown Source)
[info]   at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
[info]   at java.lang.ClassLoader.loadClass(Unknown Source)
[info]   at cats.free.Free$.catsFreeMonadForFree(Free.scala:247)
[info]   at org.packag3.controllers.Utils.$anonfun$camelizeJsonKeys$7(Utils.scala:53)
[info]   at io.circe.Json.arrayOrObject(Json.scala:55)
[info]   at org.packag3.controllers.Utils.transformKeys$1(Utils.scala:53)
[info]   at org.packag3.controllers.Utils.camelizeJsonKeys(Utils.scala:57)
[info]   at org.packag3.controllers.Utils.camelizeJsonKeys$(Utils.scala:40)

```
which runs just fine on -M1. Using play framework 2.6.7 with Scala 2.12.4 if it counts.

**Comment by travisbrown** [comment]
This looks like you're pulling in a Cats 1.0.0-MF dependency (or a library that depends on 1.0.0-MF), while M2 depends on Cats 1.0.0-RC1. Sorry about the frustration—soon we'll have a Cats 1.0 and won't have to worry about this kind of thing for a while.
